name: qNLP
channels:
  - conda-forge
dependencies:
  - appnope=0.1.3
  - asttokens=2.4.1
  - ca-certificates=2023.11.17
  - cloudpickle=3.0.0
  - comm=0.2.1
  - debugpy=1.8.0
  - decorator=5.1.1
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - ipykernel=6.29.0
  - ipython=8.18.1
  - jedi=0.19.1
  - jupyter_client=8.6.0
  - jupyter_core=5.7.1
  - libcxx=16.0.6
  - libffi=3.3
  - libsodium=1.0.18
  - libsqlite=3.44.2
  - libzlib=1.2.13
  - matplotlib-inline=0.1.6
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=1.1.1w
  - packaging=23.2
  - parso=0.8.3
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=23.3.2
  - platformdirs=4.1.0
  - prompt-toolkit=3.0.42
  - psutil=5.9.8
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.17.2
  - python=3.9.0
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pyzmq=25.1.2
  - readline=8.2
  - setuptools=69.0.3
  - six=1.16.0
  - spyder-kernels=2.1.0
  - sqlite=3.44.2
  - stack_data=0.6.2
  - tk=8.6.13
  - tornado=6.3.3
  - traitlets=5.14.1
  - typing_extensions=4.9.0
  - tzdata=2023d
  - wcwidth=0.2.13
  - wheel=0.42.0
  - wurlitzer=3.0.3
  - xz=5.2.6
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - pip:
      - annotated-types==0.6.0
      - blis==0.7.11
      - catalogue==2.0.10
      - certifi==2023.11.17
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cloudpathlib==0.16.0
      - confection==0.1.4
      - contourpy==1.2.0
      - cryptography==42.0.1
      - cycler==0.12.1
      - cymem==2.0.8
      - dill==0.3.7
      - discopy==1.1.6
      - filelock==3.13.1
      - fonttools==4.47.2
      - fsspec==2023.12.2
      - h5py==3.10.0
      - huggingface-hub==0.20.3
      - ibm-cloud-sdk-core==3.19.1
      - ibm-platform-services==0.49.0
      - idna==3.6
      - importlib-resources==6.1.1
      - jinja2==3.1.3
      - kiwisolver==1.4.5
      - lambeq==0.4.0
      - langcodes==3.3.0
      - lark-parser==0.12.0
      - markupsafe==2.1.4
      - matplotlib==3.8.2
      - mplhep==0.3.32
      - mplhep-data==0.0.3
      - mpmath==1.3.0
      - murmurhash==1.0.10
      - networkx==3.2.1
      - numpy==1.26.3
      - opt-einsum==3.3.0
      - pbr==6.0.0
      - pillow==10.2.0
      - ply==3.11
      - preshed==3.0.9
      - pycparser==2.21
      - pydantic==2.5.3
      - pydantic-core==2.14.6
      - pyjwt==2.8.0
      - pyparsing==3.1.1
      - pyspnego==0.10.2
      - python-graphviz==0.20.1
      - pytket==1.23.0
      - pytket-qiskit==0.47.0
      - pyyaml==6.0.1
      - qiskit==0.45.2
      - qiskit-aer==0.13.2
      - qiskit-algorithms==0.2.2
      - qiskit-ibm-provider==0.8.0
      - qiskit-ibm-runtime==0.17.0
      - qiskit-terra==0.45.2
      - qwasm==1.0.1
      - regex==2023.12.25
      - requests==2.31.0
      - requests-ntlm==1.2.0
      - rustworkx==0.14.0
      - safetensors==0.4.2
      - scipy==1.12.0
      - smart-open==6.4.0
      - spacy==3.7.2
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.4.8
      - stevedore==5.1.0
      - symengine==0.11.0
      - sympy==1.12
      - tensornetwork==0.4.6
      - thinc==8.2.2
      - tokenizers==0.15.1
      - torch==2.1.2
      - tqdm==4.66.1
      - transformers==4.37.1
      - typer==0.9.0
      - types-pkg-resources==0.1.3
      - uhi==0.4.0
      - urllib3==2.1.0
      - wasabi==1.1.2
      - weasel==0.3.4
      - websocket-client==1.7.0
      - websockets==12.0
